package kubernetes

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	admissionregistrationv1 "k8s.io/kubernetes/pkg/apis/admissionregistration/v1"
	admissionregistrationv1alpha1 "k8s.io/kubernetes/pkg/apis/admissionregistration/v1alpha1"
	admissionregistrationv1beta1 "k8s.io/kubernetes/pkg/apis/admissionregistration/v1beta1"
	apidiscoveryv2 "k8s.io/kubernetes/pkg/apis/apidiscovery/v2"
	apidiscoveryv2beta1 "k8s.io/kubernetes/pkg/apis/apidiscovery/v2beta1"
	apiserverinternalv1alpha1 "k8s.io/kubernetes/pkg/apis/apiserverinternal/v1alpha1"
	appsv1 "k8s.io/kubernetes/pkg/apis/apps/v1"
	appsv1beta1 "k8s.io/kubernetes/pkg/apis/apps/v1beta1"
	appsv1beta2 "k8s.io/kubernetes/pkg/apis/apps/v1beta2"
	authenticationv1 "k8s.io/kubernetes/pkg/apis/authentication/v1"
	authenticationv1alpha1 "k8s.io/kubernetes/pkg/apis/authentication/v1alpha1"
	authenticationv1beta1 "k8s.io/kubernetes/pkg/apis/authentication/v1beta1"
	authorizationv1 "k8s.io/kubernetes/pkg/apis/authorization/v1"
	authorizationv1beta1 "k8s.io/kubernetes/pkg/apis/authorization/v1beta1"
	autoscalingv1 "k8s.io/kubernetes/pkg/apis/autoscaling/v1"
	autoscalingv2 "k8s.io/kubernetes/pkg/apis/autoscaling/v2"
	autoscalingv2beta1 "k8s.io/kubernetes/pkg/apis/autoscaling/v2beta1"
	autoscalingv2beta2 "k8s.io/kubernetes/pkg/apis/autoscaling/v2beta2"
	batchv1 "k8s.io/kubernetes/pkg/apis/batch/v1"
	batchv1beta1 "k8s.io/kubernetes/pkg/apis/batch/v1beta1"
	certificatesv1 "k8s.io/kubernetes/pkg/apis/certificates/v1"
	certificatesv1alpha1 "k8s.io/kubernetes/pkg/apis/certificates/v1alpha1"
	certificatesv1beta1 "k8s.io/kubernetes/pkg/apis/certificates/v1beta1"
	coordinationv1 "k8s.io/kubernetes/pkg/apis/coordination/v1"
	coordinationv1beta1 "k8s.io/kubernetes/pkg/apis/coordination/v1beta1"
	corev1 "k8s.io/kubernetes/pkg/apis/core/v1"
	discoveryv1 "k8s.io/kubernetes/pkg/apis/discovery/v1"
	discoveryv1beta1 "k8s.io/kubernetes/pkg/apis/discovery/v1beta1"
	eventsv1 "k8s.io/kubernetes/pkg/apis/events/v1"
	eventsv1beta1 "k8s.io/kubernetes/pkg/apis/events/v1beta1"
	extensionsv1beta1 "k8s.io/kubernetes/pkg/apis/extensions/v1beta1"
	flowcontrolv1 "k8s.io/kubernetes/pkg/apis/flowcontrol/v1"
	flowcontrolv1beta1 "k8s.io/kubernetes/pkg/apis/flowcontrol/v1beta1"
	flowcontrolv1beta2 "k8s.io/kubernetes/pkg/apis/flowcontrol/v1beta2"
	flowcontrolv1beta3 "k8s.io/kubernetes/pkg/apis/flowcontrol/v1beta3"
	imagepolicyv1alpha1 "k8s.io/kubernetes/pkg/apis/imagepolicy/v1alpha1"
	networkingv1 "k8s.io/kubernetes/pkg/apis/networking/v1"
	networkingv1alpha1 "k8s.io/kubernetes/pkg/apis/networking/v1alpha1"
	networkingv1beta1 "k8s.io/kubernetes/pkg/apis/networking/v1beta1"
	nodev1 "k8s.io/kubernetes/pkg/apis/node/v1"
	nodev1alpha1 "k8s.io/kubernetes/pkg/apis/node/v1alpha1"
	nodev1beta1 "k8s.io/kubernetes/pkg/apis/node/v1beta1"
	policyv1 "k8s.io/kubernetes/pkg/apis/policy/v1"
	policyv1beta1 "k8s.io/kubernetes/pkg/apis/policy/v1beta1"
	rbacv1 "k8s.io/kubernetes/pkg/apis/rbac/v1"
	rbacv1alpha1 "k8s.io/kubernetes/pkg/apis/rbac/v1alpha1"
	rbacv1beta1 "k8s.io/kubernetes/pkg/apis/rbac/v1beta1"
	resourcev1alpha2 "k8s.io/kubernetes/pkg/apis/resource/v1alpha2"
	schedulingv1 "k8s.io/kubernetes/pkg/apis/scheduling/v1"
	schedulingv1alpha1 "k8s.io/kubernetes/pkg/apis/scheduling/v1alpha1"
	schedulingv1beta1 "k8s.io/kubernetes/pkg/apis/scheduling/v1beta1"
	storagev1 "k8s.io/kubernetes/pkg/apis/storage/v1"
	storagev1alpha1 "k8s.io/kubernetes/pkg/apis/storage/v1alpha1"
	storagev1beta1 "k8s.io/kubernetes/pkg/apis/storage/v1beta1"
	storagemigrationv1alpha1 "k8s.io/kubernetes/pkg/apis/storagemigration/v1alpha1"
)

var UnstructuredListToTableFuncs = map[schema.GroupVersionKind]func(*unstructured.UnstructuredList) (*metav1.Table, error){
	admissionregistrationv1.SchemeGroupVersion.WithKind("MutatingWebhookConfigurationList"):           UnstructuredListToTableFunc(AdmissionregistrationV1MutatingWebhookConfigurationListToTable),
	admissionregistrationv1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicyBindingList"):       UnstructuredListToTableFunc(AdmissionregistrationV1ValidatingAdmissionPolicyBindingListToTable),
	admissionregistrationv1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicyList"):              UnstructuredListToTableFunc(AdmissionregistrationV1ValidatingAdmissionPolicyListToTable),
	admissionregistrationv1.SchemeGroupVersion.WithKind("ValidatingWebhookConfigurationList"):         UnstructuredListToTableFunc(AdmissionregistrationV1ValidatingWebhookConfigurationListToTable),
	admissionregistrationv1alpha1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicyBindingList"): UnstructuredListToTableFunc(AdmissionregistrationV1alpha1ValidatingAdmissionPolicyBindingListToTable),
	admissionregistrationv1alpha1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicyList"):        UnstructuredListToTableFunc(AdmissionregistrationV1alpha1ValidatingAdmissionPolicyListToTable),
	admissionregistrationv1beta1.SchemeGroupVersion.WithKind("MutatingWebhookConfigurationList"):      UnstructuredListToTableFunc(AdmissionregistrationV1beta1MutatingWebhookConfigurationListToTable),
	admissionregistrationv1beta1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicyBindingList"):  UnstructuredListToTableFunc(AdmissionregistrationV1beta1ValidatingAdmissionPolicyBindingListToTable),
	admissionregistrationv1beta1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicyList"):         UnstructuredListToTableFunc(AdmissionregistrationV1beta1ValidatingAdmissionPolicyListToTable),
	admissionregistrationv1beta1.SchemeGroupVersion.WithKind("ValidatingWebhookConfigurationList"):    UnstructuredListToTableFunc(AdmissionregistrationV1beta1ValidatingWebhookConfigurationListToTable),
	apidiscoveryv2.SchemeGroupVersion.WithKind("APIGroupDiscoveryList"):                               UnstructuredListToTableFunc(ApidiscoveryV2APIGroupDiscoveryListToTable),
	apidiscoveryv2beta1.SchemeGroupVersion.WithKind("APIGroupDiscoveryList"):                          UnstructuredListToTableFunc(ApidiscoveryV2beta1APIGroupDiscoveryListToTable),
	apiserverinternalv1alpha1.SchemeGroupVersion.WithKind("StorageVersionList"):                       UnstructuredListToTableFunc(ApiserverinternalV1alpha1StorageVersionListToTable),
	corev1.SchemeGroupVersion.WithKind("ComponentStatusList"):                                         UnstructuredListToTableFunc(CoreV1ComponentStatusListToTable),
	corev1.SchemeGroupVersion.WithKind("ConfigMapList"):                                               UnstructuredListToTableFunc(CoreV1ConfigMapListToTable),
	corev1.SchemeGroupVersion.WithKind("EndpointsList"):                                               UnstructuredListToTableFunc(CoreV1EndpointsListToTable),
	corev1.SchemeGroupVersion.WithKind("EventList"):                                                   UnstructuredListToTableFunc(CoreV1EventListToTable),
	corev1.SchemeGroupVersion.WithKind("LimitRangeList"):                                              UnstructuredListToTableFunc(CoreV1LimitRangeListToTable),
	corev1.SchemeGroupVersion.WithKind("List"):                                                        UnstructuredListToTableFunc(CoreV1ListToTable),
	corev1.SchemeGroupVersion.WithKind("NamespaceList"):                                               UnstructuredListToTableFunc(CoreV1NamespaceListToTable),
	corev1.SchemeGroupVersion.WithKind("NodeList"):                                                    UnstructuredListToTableFunc(CoreV1NodeListToTable),
	corev1.SchemeGroupVersion.WithKind("PersistentVolumeClaimList"):                                   UnstructuredListToTableFunc(CoreV1PersistentVolumeClaimListToTable),
	corev1.SchemeGroupVersion.WithKind("PersistentVolumeList"):                                        UnstructuredListToTableFunc(CoreV1PersistentVolumeListToTable),
	corev1.SchemeGroupVersion.WithKind("PodList"):                                                     UnstructuredListToTableFunc(CoreV1PodListToTable),
	corev1.SchemeGroupVersion.WithKind("PodTemplateList"):                                             UnstructuredListToTableFunc(CoreV1PodTemplateListToTable),
	corev1.SchemeGroupVersion.WithKind("ReplicationControllerList"):                                   UnstructuredListToTableFunc(CoreV1ReplicationControllerListToTable),
	corev1.SchemeGroupVersion.WithKind("ResourceQuotaList"):                                           UnstructuredListToTableFunc(CoreV1ResourceQuotaListToTable),
	corev1.SchemeGroupVersion.WithKind("SecretList"):                                                  UnstructuredListToTableFunc(CoreV1SecretListToTable),
	corev1.SchemeGroupVersion.WithKind("ServiceAccountList"):                                          UnstructuredListToTableFunc(CoreV1ServiceAccountListToTable),
	corev1.SchemeGroupVersion.WithKind("ServiceList"):                                                 UnstructuredListToTableFunc(CoreV1ServiceListToTable),
	appsv1.SchemeGroupVersion.WithKind("ControllerRevisionList"):                                      UnstructuredListToTableFunc(AppsV1ControllerRevisionListToTable),
	appsv1.SchemeGroupVersion.WithKind("DaemonSetList"):                                               UnstructuredListToTableFunc(AppsV1DaemonSetListToTable),
	appsv1.SchemeGroupVersion.WithKind("DeploymentList"):                                              UnstructuredListToTableFunc(AppsV1DeploymentListToTable),
	appsv1.SchemeGroupVersion.WithKind("ReplicaSetList"):                                              UnstructuredListToTableFunc(AppsV1ReplicaSetListToTable),
	appsv1.SchemeGroupVersion.WithKind("StatefulSetList"):                                             UnstructuredListToTableFunc(AppsV1StatefulSetListToTable),
	appsv1beta1.SchemeGroupVersion.WithKind("ControllerRevisionList"):                                 UnstructuredListToTableFunc(AppsV1beta1ControllerRevisionListToTable),
	appsv1beta1.SchemeGroupVersion.WithKind("DeploymentList"):                                         UnstructuredListToTableFunc(AppsV1beta1DeploymentListToTable),
	appsv1beta1.SchemeGroupVersion.WithKind("StatefulSetList"):                                        UnstructuredListToTableFunc(AppsV1beta1StatefulSetListToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("ControllerRevisionList"):                                 UnstructuredListToTableFunc(AppsV1beta2ControllerRevisionListToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("DaemonSetList"):                                          UnstructuredListToTableFunc(AppsV1beta2DaemonSetListToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("DeploymentList"):                                         UnstructuredListToTableFunc(AppsV1beta2DeploymentListToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("ReplicaSetList"):                                         UnstructuredListToTableFunc(AppsV1beta2ReplicaSetListToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("StatefulSetList"):                                        UnstructuredListToTableFunc(AppsV1beta2StatefulSetListToTable),
	autoscalingv1.SchemeGroupVersion.WithKind("HorizontalPodAutoscalerList"):                          UnstructuredListToTableFunc(AutoscalingV1HorizontalPodAutoscalerListToTable),
	autoscalingv2.SchemeGroupVersion.WithKind("HorizontalPodAutoscalerList"):                          UnstructuredListToTableFunc(AutoscalingV2HorizontalPodAutoscalerListToTable),
	autoscalingv2beta1.SchemeGroupVersion.WithKind("HorizontalPodAutoscalerList"):                     UnstructuredListToTableFunc(AutoscalingV2beta1HorizontalPodAutoscalerListToTable),
	autoscalingv2beta2.SchemeGroupVersion.WithKind("HorizontalPodAutoscalerList"):                     UnstructuredListToTableFunc(AutoscalingV2beta2HorizontalPodAutoscalerListToTable),
	batchv1.SchemeGroupVersion.WithKind("CronJobList"):                                                UnstructuredListToTableFunc(BatchV1CronJobListToTable),
	batchv1.SchemeGroupVersion.WithKind("JobList"):                                                    UnstructuredListToTableFunc(BatchV1JobListToTable),
	batchv1beta1.SchemeGroupVersion.WithKind("CronJobList"):                                           UnstructuredListToTableFunc(BatchV1beta1CronJobListToTable),
	certificatesv1.SchemeGroupVersion.WithKind("CertificateSigningRequestList"):                       UnstructuredListToTableFunc(CertificatesV1CertificateSigningRequestListToTable),
	certificatesv1alpha1.SchemeGroupVersion.WithKind("ClusterTrustBundleList"):                        UnstructuredListToTableFunc(CertificatesV1alpha1ClusterTrustBundleListToTable),
	certificatesv1beta1.SchemeGroupVersion.WithKind("CertificateSigningRequestList"):                  UnstructuredListToTableFunc(CertificatesV1beta1CertificateSigningRequestListToTable),
	coordinationv1.SchemeGroupVersion.WithKind("LeaseList"):                                           UnstructuredListToTableFunc(CoordinationV1LeaseListToTable),
	coordinationv1beta1.SchemeGroupVersion.WithKind("LeaseList"):                                      UnstructuredListToTableFunc(CoordinationV1beta1LeaseListToTable),
	discoveryv1.SchemeGroupVersion.WithKind("EndpointSliceList"):                                      UnstructuredListToTableFunc(DiscoveryV1EndpointSliceListToTable),
	discoveryv1beta1.SchemeGroupVersion.WithKind("EndpointSliceList"):                                 UnstructuredListToTableFunc(DiscoveryV1beta1EndpointSliceListToTable),
	eventsv1.SchemeGroupVersion.WithKind("EventList"):                                                 UnstructuredListToTableFunc(EventsV1EventListToTable),
	eventsv1beta1.SchemeGroupVersion.WithKind("EventList"):                                            UnstructuredListToTableFunc(EventsV1beta1EventListToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("DaemonSetList"):                                    UnstructuredListToTableFunc(ExtensionsV1beta1DaemonSetListToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("DeploymentList"):                                   UnstructuredListToTableFunc(ExtensionsV1beta1DeploymentListToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("IngressList"):                                      UnstructuredListToTableFunc(ExtensionsV1beta1IngressListToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("NetworkPolicyList"):                                UnstructuredListToTableFunc(ExtensionsV1beta1NetworkPolicyListToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("ReplicaSetList"):                                   UnstructuredListToTableFunc(ExtensionsV1beta1ReplicaSetListToTable),
	flowcontrolv1.SchemeGroupVersion.WithKind("FlowSchemaList"):                                       UnstructuredListToTableFunc(FlowcontrolV1FlowSchemaListToTable),
	flowcontrolv1.SchemeGroupVersion.WithKind("PriorityLevelConfigurationList"):                       UnstructuredListToTableFunc(FlowcontrolV1PriorityLevelConfigurationListToTable),
	flowcontrolv1beta1.SchemeGroupVersion.WithKind("FlowSchemaList"):                                  UnstructuredListToTableFunc(FlowcontrolV1beta1FlowSchemaListToTable),
	flowcontrolv1beta1.SchemeGroupVersion.WithKind("PriorityLevelConfigurationList"):                  UnstructuredListToTableFunc(FlowcontrolV1beta1PriorityLevelConfigurationListToTable),
	flowcontrolv1beta2.SchemeGroupVersion.WithKind("FlowSchemaList"):                                  UnstructuredListToTableFunc(FlowcontrolV1beta2FlowSchemaListToTable),
	flowcontrolv1beta2.SchemeGroupVersion.WithKind("PriorityLevelConfigurationList"):                  UnstructuredListToTableFunc(FlowcontrolV1beta2PriorityLevelConfigurationListToTable),
	flowcontrolv1beta3.SchemeGroupVersion.WithKind("FlowSchemaList"):                                  UnstructuredListToTableFunc(FlowcontrolV1beta3FlowSchemaListToTable),
	flowcontrolv1beta3.SchemeGroupVersion.WithKind("PriorityLevelConfigurationList"):                  UnstructuredListToTableFunc(FlowcontrolV1beta3PriorityLevelConfigurationListToTable),
	networkingv1.SchemeGroupVersion.WithKind("IngressClassList"):                                      UnstructuredListToTableFunc(NetworkingV1IngressClassListToTable),
	networkingv1.SchemeGroupVersion.WithKind("IngressList"):                                           UnstructuredListToTableFunc(NetworkingV1IngressListToTable),
	networkingv1.SchemeGroupVersion.WithKind("NetworkPolicyList"):                                     UnstructuredListToTableFunc(NetworkingV1NetworkPolicyListToTable),
	networkingv1alpha1.SchemeGroupVersion.WithKind("IPAddressList"):                                   UnstructuredListToTableFunc(NetworkingV1alpha1IPAddressListToTable),
	networkingv1alpha1.SchemeGroupVersion.WithKind("ServiceCIDRList"):                                 UnstructuredListToTableFunc(NetworkingV1alpha1ServiceCIDRListToTable),
	networkingv1beta1.SchemeGroupVersion.WithKind("IngressClassList"):                                 UnstructuredListToTableFunc(NetworkingV1beta1IngressClassListToTable),
	networkingv1beta1.SchemeGroupVersion.WithKind("IngressList"):                                      UnstructuredListToTableFunc(NetworkingV1beta1IngressListToTable),
	nodev1.SchemeGroupVersion.WithKind("RuntimeClassList"):                                            UnstructuredListToTableFunc(NodeV1RuntimeClassListToTable),
	nodev1alpha1.SchemeGroupVersion.WithKind("RuntimeClassList"):                                      UnstructuredListToTableFunc(NodeV1alpha1RuntimeClassListToTable),
	nodev1beta1.SchemeGroupVersion.WithKind("RuntimeClassList"):                                       UnstructuredListToTableFunc(NodeV1beta1RuntimeClassListToTable),
	policyv1.SchemeGroupVersion.WithKind("PodDisruptionBudgetList"):                                   UnstructuredListToTableFunc(PolicyV1PodDisruptionBudgetListToTable),
	policyv1beta1.SchemeGroupVersion.WithKind("PodDisruptionBudgetList"):                              UnstructuredListToTableFunc(PolicyV1beta1PodDisruptionBudgetListToTable),
	rbacv1.SchemeGroupVersion.WithKind("ClusterRoleBindingList"):                                      UnstructuredListToTableFunc(RbacV1ClusterRoleBindingListToTable),
	rbacv1.SchemeGroupVersion.WithKind("ClusterRoleList"):                                             UnstructuredListToTableFunc(RbacV1ClusterRoleListToTable),
	rbacv1.SchemeGroupVersion.WithKind("RoleBindingList"):                                             UnstructuredListToTableFunc(RbacV1RoleBindingListToTable),
	rbacv1.SchemeGroupVersion.WithKind("RoleList"):                                                    UnstructuredListToTableFunc(RbacV1RoleListToTable),
	rbacv1alpha1.SchemeGroupVersion.WithKind("ClusterRoleBindingList"):                                UnstructuredListToTableFunc(RbacV1alpha1ClusterRoleBindingListToTable),
	rbacv1alpha1.SchemeGroupVersion.WithKind("ClusterRoleList"):                                       UnstructuredListToTableFunc(RbacV1alpha1ClusterRoleListToTable),
	rbacv1alpha1.SchemeGroupVersion.WithKind("RoleBindingList"):                                       UnstructuredListToTableFunc(RbacV1alpha1RoleBindingListToTable),
	rbacv1alpha1.SchemeGroupVersion.WithKind("RoleList"):                                              UnstructuredListToTableFunc(RbacV1alpha1RoleListToTable),
	rbacv1beta1.SchemeGroupVersion.WithKind("ClusterRoleBindingList"):                                 UnstructuredListToTableFunc(RbacV1beta1ClusterRoleBindingListToTable),
	rbacv1beta1.SchemeGroupVersion.WithKind("ClusterRoleList"):                                        UnstructuredListToTableFunc(RbacV1beta1ClusterRoleListToTable),
	rbacv1beta1.SchemeGroupVersion.WithKind("RoleBindingList"):                                        UnstructuredListToTableFunc(RbacV1beta1RoleBindingListToTable),
	rbacv1beta1.SchemeGroupVersion.WithKind("RoleList"):                                               UnstructuredListToTableFunc(RbacV1beta1RoleListToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("PodSchedulingContextList"):                          UnstructuredListToTableFunc(ResourceV1alpha2PodSchedulingContextListToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClaimList"):                                 UnstructuredListToTableFunc(ResourceV1alpha2ResourceClaimListToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClaimParametersList"):                       UnstructuredListToTableFunc(ResourceV1alpha2ResourceClaimParametersListToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClaimTemplateList"):                         UnstructuredListToTableFunc(ResourceV1alpha2ResourceClaimTemplateListToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClassList"):                                 UnstructuredListToTableFunc(ResourceV1alpha2ResourceClassListToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClassParametersList"):                       UnstructuredListToTableFunc(ResourceV1alpha2ResourceClassParametersListToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceSliceList"):                                 UnstructuredListToTableFunc(ResourceV1alpha2ResourceSliceListToTable),
	schedulingv1.SchemeGroupVersion.WithKind("PriorityClassList"):                                     UnstructuredListToTableFunc(SchedulingV1PriorityClassListToTable),
	schedulingv1alpha1.SchemeGroupVersion.WithKind("PriorityClassList"):                               UnstructuredListToTableFunc(SchedulingV1alpha1PriorityClassListToTable),
	schedulingv1beta1.SchemeGroupVersion.WithKind("PriorityClassList"):                                UnstructuredListToTableFunc(SchedulingV1beta1PriorityClassListToTable),
	storagev1.SchemeGroupVersion.WithKind("CSIDriverList"):                                            UnstructuredListToTableFunc(StorageV1CSIDriverListToTable),
	storagev1.SchemeGroupVersion.WithKind("CSINodeList"):                                              UnstructuredListToTableFunc(StorageV1CSINodeListToTable),
	storagev1.SchemeGroupVersion.WithKind("CSIStorageCapacityList"):                                   UnstructuredListToTableFunc(StorageV1CSIStorageCapacityListToTable),
	storagev1.SchemeGroupVersion.WithKind("StorageClassList"):                                         UnstructuredListToTableFunc(StorageV1StorageClassListToTable),
	storagev1.SchemeGroupVersion.WithKind("VolumeAttachmentList"):                                     UnstructuredListToTableFunc(StorageV1VolumeAttachmentListToTable),
	storagev1alpha1.SchemeGroupVersion.WithKind("CSIStorageCapacityList"):                             UnstructuredListToTableFunc(StorageV1alpha1CSIStorageCapacityListToTable),
	storagev1alpha1.SchemeGroupVersion.WithKind("VolumeAttachmentList"):                               UnstructuredListToTableFunc(StorageV1alpha1VolumeAttachmentListToTable),
	storagev1alpha1.SchemeGroupVersion.WithKind("VolumeAttributesClassList"):                          UnstructuredListToTableFunc(StorageV1alpha1VolumeAttributesClassListToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("CSIDriverList"):                                       UnstructuredListToTableFunc(StorageV1beta1CSIDriverListToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("CSINodeList"):                                         UnstructuredListToTableFunc(StorageV1beta1CSINodeListToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("CSIStorageCapacityList"):                              UnstructuredListToTableFunc(StorageV1beta1CSIStorageCapacityListToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("StorageClassList"):                                    UnstructuredListToTableFunc(StorageV1beta1StorageClassListToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("VolumeAttachmentList"):                                UnstructuredListToTableFunc(StorageV1beta1VolumeAttachmentListToTable),
	storagemigrationv1alpha1.SchemeGroupVersion.WithKind("StorageVersionMigrationList"):               UnstructuredListToTableFunc(StoragemigrationV1alpha1StorageVersionMigrationListToTable),
}
var UnstructuredToTableFuncs = map[schema.GroupVersionKind]func(*unstructured.Unstructured) (*metav1.Table, error){
	authenticationv1.SchemeGroupVersion.WithKind("SelfSubjectReview"):                             UnstructuredToTableFunc(AuthenticationV1SelfSubjectReviewToTable),
	authenticationv1.SchemeGroupVersion.WithKind("TokenRequest"):                                  UnstructuredToTableFunc(AuthenticationV1TokenRequestToTable),
	authenticationv1.SchemeGroupVersion.WithKind("TokenReview"):                                   UnstructuredToTableFunc(AuthenticationV1TokenReviewToTable),
	admissionregistrationv1.SchemeGroupVersion.WithKind("MutatingWebhookConfiguration"):           UnstructuredToTableFunc(AdmissionregistrationV1MutatingWebhookConfigurationToTable),
	admissionregistrationv1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicyBinding"):       UnstructuredToTableFunc(AdmissionregistrationV1ValidatingAdmissionPolicyBindingToTable),
	admissionregistrationv1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicy"):              UnstructuredToTableFunc(AdmissionregistrationV1ValidatingAdmissionPolicyToTable),
	admissionregistrationv1.SchemeGroupVersion.WithKind("ValidatingWebhookConfiguration"):         UnstructuredToTableFunc(AdmissionregistrationV1ValidatingWebhookConfigurationToTable),
	admissionregistrationv1alpha1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicyBinding"): UnstructuredToTableFunc(AdmissionregistrationV1alpha1ValidatingAdmissionPolicyBindingToTable),
	admissionregistrationv1alpha1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicy"):        UnstructuredToTableFunc(AdmissionregistrationV1alpha1ValidatingAdmissionPolicyToTable),
	admissionregistrationv1beta1.SchemeGroupVersion.WithKind("MutatingWebhookConfiguration"):      UnstructuredToTableFunc(AdmissionregistrationV1beta1MutatingWebhookConfigurationToTable),
	admissionregistrationv1beta1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicyBinding"):  UnstructuredToTableFunc(AdmissionregistrationV1beta1ValidatingAdmissionPolicyBindingToTable),
	admissionregistrationv1beta1.SchemeGroupVersion.WithKind("ValidatingAdmissionPolicy"):         UnstructuredToTableFunc(AdmissionregistrationV1beta1ValidatingAdmissionPolicyToTable),
	admissionregistrationv1beta1.SchemeGroupVersion.WithKind("ValidatingWebhookConfiguration"):    UnstructuredToTableFunc(AdmissionregistrationV1beta1ValidatingWebhookConfigurationToTable),
	apidiscoveryv2.SchemeGroupVersion.WithKind("APIGroupDiscovery"):                               UnstructuredToTableFunc(ApidiscoveryV2APIGroupDiscoveryToTable),
	apidiscoveryv2beta1.SchemeGroupVersion.WithKind("APIGroupDiscovery"):                          UnstructuredToTableFunc(ApidiscoveryV2beta1APIGroupDiscoveryToTable),
	apiserverinternalv1alpha1.SchemeGroupVersion.WithKind("StorageVersion"):                       UnstructuredToTableFunc(ApiserverinternalV1alpha1StorageVersionToTable),
	corev1.SchemeGroupVersion.WithKind("Binding"):                                                 UnstructuredToTableFunc(CoreV1BindingToTable),
	corev1.SchemeGroupVersion.WithKind("ComponentStatus"):                                         UnstructuredToTableFunc(CoreV1ComponentStatusToTable),
	corev1.SchemeGroupVersion.WithKind("ConfigMap"):                                               UnstructuredToTableFunc(CoreV1ConfigMapToTable),
	corev1.SchemeGroupVersion.WithKind("Endpoints"):                                               UnstructuredToTableFunc(CoreV1EndpointsToTable),
	corev1.SchemeGroupVersion.WithKind("Event"):                                                   UnstructuredToTableFunc(CoreV1EventToTable),
	corev1.SchemeGroupVersion.WithKind("LimitRange"):                                              UnstructuredToTableFunc(CoreV1LimitRangeToTable),
	corev1.SchemeGroupVersion.WithKind("Namespace"):                                               UnstructuredToTableFunc(CoreV1NamespaceToTable),
	corev1.SchemeGroupVersion.WithKind("Node"):                                                    UnstructuredToTableFunc(CoreV1NodeToTable),
	corev1.SchemeGroupVersion.WithKind("PersistentVolumeClaim"):                                   UnstructuredToTableFunc(CoreV1PersistentVolumeClaimToTable),
	corev1.SchemeGroupVersion.WithKind("PersistentVolume"):                                        UnstructuredToTableFunc(CoreV1PersistentVolumeToTable),
	corev1.SchemeGroupVersion.WithKind("PodStatusResult"):                                         UnstructuredToTableFunc(CoreV1PodStatusResultToTable),
	corev1.SchemeGroupVersion.WithKind("PodTemplate"):                                             UnstructuredToTableFunc(CoreV1PodTemplateToTable),
	corev1.SchemeGroupVersion.WithKind("Pod"):                                                     UnstructuredToTableFunc(CoreV1PodToTable),
	corev1.SchemeGroupVersion.WithKind("RangeAllocation"):                                         UnstructuredToTableFunc(CoreV1RangeAllocationToTable),
	corev1.SchemeGroupVersion.WithKind("ReplicationController"):                                   UnstructuredToTableFunc(CoreV1ReplicationControllerToTable),
	corev1.SchemeGroupVersion.WithKind("ResourceQuota"):                                           UnstructuredToTableFunc(CoreV1ResourceQuotaToTable),
	corev1.SchemeGroupVersion.WithKind("Secret"):                                                  UnstructuredToTableFunc(CoreV1SecretToTable),
	corev1.SchemeGroupVersion.WithKind("ServiceAccount"):                                          UnstructuredToTableFunc(CoreV1ServiceAccountToTable),
	corev1.SchemeGroupVersion.WithKind("Service"):                                                 UnstructuredToTableFunc(CoreV1ServiceToTable),
	appsv1.SchemeGroupVersion.WithKind("ControllerRevision"):                                      UnstructuredToTableFunc(AppsV1ControllerRevisionToTable),
	appsv1.SchemeGroupVersion.WithKind("DaemonSet"):                                               UnstructuredToTableFunc(AppsV1DaemonSetToTable),
	appsv1.SchemeGroupVersion.WithKind("Deployment"):                                              UnstructuredToTableFunc(AppsV1DeploymentToTable),
	appsv1.SchemeGroupVersion.WithKind("ReplicaSet"):                                              UnstructuredToTableFunc(AppsV1ReplicaSetToTable),
	appsv1.SchemeGroupVersion.WithKind("StatefulSet"):                                             UnstructuredToTableFunc(AppsV1StatefulSetToTable),
	appsv1beta1.SchemeGroupVersion.WithKind("ControllerRevision"):                                 UnstructuredToTableFunc(AppsV1beta1ControllerRevisionToTable),
	appsv1beta1.SchemeGroupVersion.WithKind("Deployment"):                                         UnstructuredToTableFunc(AppsV1beta1DeploymentToTable),
	appsv1beta1.SchemeGroupVersion.WithKind("Scale"):                                              UnstructuredToTableFunc(AppsV1beta1ScaleToTable),
	appsv1beta1.SchemeGroupVersion.WithKind("StatefulSet"):                                        UnstructuredToTableFunc(AppsV1beta1StatefulSetToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("ControllerRevision"):                                 UnstructuredToTableFunc(AppsV1beta2ControllerRevisionToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("DaemonSet"):                                          UnstructuredToTableFunc(AppsV1beta2DaemonSetToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("Deployment"):                                         UnstructuredToTableFunc(AppsV1beta2DeploymentToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("ReplicaSet"):                                         UnstructuredToTableFunc(AppsV1beta2ReplicaSetToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("Scale"):                                              UnstructuredToTableFunc(AppsV1beta2ScaleToTable),
	appsv1beta2.SchemeGroupVersion.WithKind("StatefulSet"):                                        UnstructuredToTableFunc(AppsV1beta2StatefulSetToTable),
	authenticationv1alpha1.SchemeGroupVersion.WithKind("SelfSubjectReview"):                       UnstructuredToTableFunc(AuthenticationV1alpha1SelfSubjectReviewToTable),
	authenticationv1beta1.SchemeGroupVersion.WithKind("SelfSubjectReview"):                        UnstructuredToTableFunc(AuthenticationV1beta1SelfSubjectReviewToTable),
	authenticationv1beta1.SchemeGroupVersion.WithKind("TokenReview"):                              UnstructuredToTableFunc(AuthenticationV1beta1TokenReviewToTable),
	authorizationv1.SchemeGroupVersion.WithKind("LocalSubjectAccessReview"):                       UnstructuredToTableFunc(AuthorizationV1LocalSubjectAccessReviewToTable),
	authorizationv1.SchemeGroupVersion.WithKind("SelfSubjectAccessReview"):                        UnstructuredToTableFunc(AuthorizationV1SelfSubjectAccessReviewToTable),
	authorizationv1.SchemeGroupVersion.WithKind("SelfSubjectRulesReview"):                         UnstructuredToTableFunc(AuthorizationV1SelfSubjectRulesReviewToTable),
	authorizationv1.SchemeGroupVersion.WithKind("SubjectAccessReview"):                            UnstructuredToTableFunc(AuthorizationV1SubjectAccessReviewToTable),
	authorizationv1beta1.SchemeGroupVersion.WithKind("LocalSubjectAccessReview"):                  UnstructuredToTableFunc(AuthorizationV1beta1LocalSubjectAccessReviewToTable),
	authorizationv1beta1.SchemeGroupVersion.WithKind("SelfSubjectAccessReview"):                   UnstructuredToTableFunc(AuthorizationV1beta1SelfSubjectAccessReviewToTable),
	authorizationv1beta1.SchemeGroupVersion.WithKind("SelfSubjectRulesReview"):                    UnstructuredToTableFunc(AuthorizationV1beta1SelfSubjectRulesReviewToTable),
	authorizationv1beta1.SchemeGroupVersion.WithKind("SubjectAccessReview"):                       UnstructuredToTableFunc(AuthorizationV1beta1SubjectAccessReviewToTable),
	autoscalingv1.SchemeGroupVersion.WithKind("HorizontalPodAutoscaler"):                          UnstructuredToTableFunc(AutoscalingV1HorizontalPodAutoscalerToTable),
	autoscalingv1.SchemeGroupVersion.WithKind("Scale"):                                            UnstructuredToTableFunc(AutoscalingV1ScaleToTable),
	autoscalingv2.SchemeGroupVersion.WithKind("HorizontalPodAutoscaler"):                          UnstructuredToTableFunc(AutoscalingV2HorizontalPodAutoscalerToTable),
	autoscalingv2beta1.SchemeGroupVersion.WithKind("HorizontalPodAutoscaler"):                     UnstructuredToTableFunc(AutoscalingV2beta1HorizontalPodAutoscalerToTable),
	autoscalingv2beta2.SchemeGroupVersion.WithKind("HorizontalPodAutoscaler"):                     UnstructuredToTableFunc(AutoscalingV2beta2HorizontalPodAutoscalerToTable),
	batchv1.SchemeGroupVersion.WithKind("CronJob"):                                                UnstructuredToTableFunc(BatchV1CronJobToTable),
	batchv1.SchemeGroupVersion.WithKind("Job"):                                                    UnstructuredToTableFunc(BatchV1JobToTable),
	batchv1beta1.SchemeGroupVersion.WithKind("CronJob"):                                           UnstructuredToTableFunc(BatchV1beta1CronJobToTable),
	certificatesv1.SchemeGroupVersion.WithKind("CertificateSigningRequest"):                       UnstructuredToTableFunc(CertificatesV1CertificateSigningRequestToTable),
	certificatesv1alpha1.SchemeGroupVersion.WithKind("ClusterTrustBundle"):                        UnstructuredToTableFunc(CertificatesV1alpha1ClusterTrustBundleToTable),
	certificatesv1beta1.SchemeGroupVersion.WithKind("CertificateSigningRequest"):                  UnstructuredToTableFunc(CertificatesV1beta1CertificateSigningRequestToTable),
	coordinationv1.SchemeGroupVersion.WithKind("Lease"):                                           UnstructuredToTableFunc(CoordinationV1LeaseToTable),
	coordinationv1beta1.SchemeGroupVersion.WithKind("Lease"):                                      UnstructuredToTableFunc(CoordinationV1beta1LeaseToTable),
	discoveryv1.SchemeGroupVersion.WithKind("EndpointSlice"):                                      UnstructuredToTableFunc(DiscoveryV1EndpointSliceToTable),
	discoveryv1beta1.SchemeGroupVersion.WithKind("EndpointSlice"):                                 UnstructuredToTableFunc(DiscoveryV1beta1EndpointSliceToTable),
	eventsv1.SchemeGroupVersion.WithKind("Event"):                                                 UnstructuredToTableFunc(EventsV1EventToTable),
	eventsv1beta1.SchemeGroupVersion.WithKind("Event"):                                            UnstructuredToTableFunc(EventsV1beta1EventToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("DaemonSet"):                                    UnstructuredToTableFunc(ExtensionsV1beta1DaemonSetToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("Deployment"):                                   UnstructuredToTableFunc(ExtensionsV1beta1DeploymentToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("Ingress"):                                      UnstructuredToTableFunc(ExtensionsV1beta1IngressToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("NetworkPolicy"):                                UnstructuredToTableFunc(ExtensionsV1beta1NetworkPolicyToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("ReplicaSet"):                                   UnstructuredToTableFunc(ExtensionsV1beta1ReplicaSetToTable),
	extensionsv1beta1.SchemeGroupVersion.WithKind("Scale"):                                        UnstructuredToTableFunc(ExtensionsV1beta1ScaleToTable),
	flowcontrolv1.SchemeGroupVersion.WithKind("FlowSchema"):                                       UnstructuredToTableFunc(FlowcontrolV1FlowSchemaToTable),
	flowcontrolv1.SchemeGroupVersion.WithKind("PriorityLevelConfiguration"):                       UnstructuredToTableFunc(FlowcontrolV1PriorityLevelConfigurationToTable),
	flowcontrolv1beta1.SchemeGroupVersion.WithKind("FlowSchema"):                                  UnstructuredToTableFunc(FlowcontrolV1beta1FlowSchemaToTable),
	flowcontrolv1beta1.SchemeGroupVersion.WithKind("PriorityLevelConfiguration"):                  UnstructuredToTableFunc(FlowcontrolV1beta1PriorityLevelConfigurationToTable),
	flowcontrolv1beta2.SchemeGroupVersion.WithKind("FlowSchema"):                                  UnstructuredToTableFunc(FlowcontrolV1beta2FlowSchemaToTable),
	flowcontrolv1beta2.SchemeGroupVersion.WithKind("PriorityLevelConfiguration"):                  UnstructuredToTableFunc(FlowcontrolV1beta2PriorityLevelConfigurationToTable),
	flowcontrolv1beta3.SchemeGroupVersion.WithKind("FlowSchema"):                                  UnstructuredToTableFunc(FlowcontrolV1beta3FlowSchemaToTable),
	flowcontrolv1beta3.SchemeGroupVersion.WithKind("PriorityLevelConfiguration"):                  UnstructuredToTableFunc(FlowcontrolV1beta3PriorityLevelConfigurationToTable),
	imagepolicyv1alpha1.SchemeGroupVersion.WithKind("ImageReview"):                                UnstructuredToTableFunc(ImagepolicyV1alpha1ImageReviewToTable),
	networkingv1.SchemeGroupVersion.WithKind("IngressClass"):                                      UnstructuredToTableFunc(NetworkingV1IngressClassToTable),
	networkingv1.SchemeGroupVersion.WithKind("Ingress"):                                           UnstructuredToTableFunc(NetworkingV1IngressToTable),
	networkingv1.SchemeGroupVersion.WithKind("NetworkPolicy"):                                     UnstructuredToTableFunc(NetworkingV1NetworkPolicyToTable),
	networkingv1alpha1.SchemeGroupVersion.WithKind("IPAddress"):                                   UnstructuredToTableFunc(NetworkingV1alpha1IPAddressToTable),
	networkingv1alpha1.SchemeGroupVersion.WithKind("ServiceCIDR"):                                 UnstructuredToTableFunc(NetworkingV1alpha1ServiceCIDRToTable),
	networkingv1beta1.SchemeGroupVersion.WithKind("IngressClass"):                                 UnstructuredToTableFunc(NetworkingV1beta1IngressClassToTable),
	networkingv1beta1.SchemeGroupVersion.WithKind("Ingress"):                                      UnstructuredToTableFunc(NetworkingV1beta1IngressToTable),
	nodev1.SchemeGroupVersion.WithKind("RuntimeClass"):                                            UnstructuredToTableFunc(NodeV1RuntimeClassToTable),
	nodev1alpha1.SchemeGroupVersion.WithKind("RuntimeClass"):                                      UnstructuredToTableFunc(NodeV1alpha1RuntimeClassToTable),
	nodev1beta1.SchemeGroupVersion.WithKind("RuntimeClass"):                                       UnstructuredToTableFunc(NodeV1beta1RuntimeClassToTable),
	policyv1.SchemeGroupVersion.WithKind("Eviction"):                                              UnstructuredToTableFunc(PolicyV1EvictionToTable),
	policyv1.SchemeGroupVersion.WithKind("PodDisruptionBudget"):                                   UnstructuredToTableFunc(PolicyV1PodDisruptionBudgetToTable),
	policyv1beta1.SchemeGroupVersion.WithKind("Eviction"):                                         UnstructuredToTableFunc(PolicyV1beta1EvictionToTable),
	policyv1beta1.SchemeGroupVersion.WithKind("PodDisruptionBudget"):                              UnstructuredToTableFunc(PolicyV1beta1PodDisruptionBudgetToTable),
	rbacv1.SchemeGroupVersion.WithKind("ClusterRoleBinding"):                                      UnstructuredToTableFunc(RbacV1ClusterRoleBindingToTable),
	rbacv1.SchemeGroupVersion.WithKind("ClusterRole"):                                             UnstructuredToTableFunc(RbacV1ClusterRoleToTable),
	rbacv1.SchemeGroupVersion.WithKind("RoleBinding"):                                             UnstructuredToTableFunc(RbacV1RoleBindingToTable),
	rbacv1.SchemeGroupVersion.WithKind("Role"):                                                    UnstructuredToTableFunc(RbacV1RoleToTable),
	rbacv1alpha1.SchemeGroupVersion.WithKind("ClusterRoleBinding"):                                UnstructuredToTableFunc(RbacV1alpha1ClusterRoleBindingToTable),
	rbacv1alpha1.SchemeGroupVersion.WithKind("ClusterRole"):                                       UnstructuredToTableFunc(RbacV1alpha1ClusterRoleToTable),
	rbacv1alpha1.SchemeGroupVersion.WithKind("RoleBinding"):                                       UnstructuredToTableFunc(RbacV1alpha1RoleBindingToTable),
	rbacv1alpha1.SchemeGroupVersion.WithKind("Role"):                                              UnstructuredToTableFunc(RbacV1alpha1RoleToTable),
	rbacv1beta1.SchemeGroupVersion.WithKind("ClusterRoleBinding"):                                 UnstructuredToTableFunc(RbacV1beta1ClusterRoleBindingToTable),
	rbacv1beta1.SchemeGroupVersion.WithKind("ClusterRole"):                                        UnstructuredToTableFunc(RbacV1beta1ClusterRoleToTable),
	rbacv1beta1.SchemeGroupVersion.WithKind("RoleBinding"):                                        UnstructuredToTableFunc(RbacV1beta1RoleBindingToTable),
	rbacv1beta1.SchemeGroupVersion.WithKind("Role"):                                               UnstructuredToTableFunc(RbacV1beta1RoleToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("PodSchedulingContext"):                          UnstructuredToTableFunc(ResourceV1alpha2PodSchedulingContextToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClaimParameters"):                       UnstructuredToTableFunc(ResourceV1alpha2ResourceClaimParametersToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClaimTemplate"):                         UnstructuredToTableFunc(ResourceV1alpha2ResourceClaimTemplateToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClaim"):                                 UnstructuredToTableFunc(ResourceV1alpha2ResourceClaimToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClassParameters"):                       UnstructuredToTableFunc(ResourceV1alpha2ResourceClassParametersToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceClass"):                                 UnstructuredToTableFunc(ResourceV1alpha2ResourceClassToTable),
	resourcev1alpha2.SchemeGroupVersion.WithKind("ResourceSlice"):                                 UnstructuredToTableFunc(ResourceV1alpha2ResourceSliceToTable),
	schedulingv1.SchemeGroupVersion.WithKind("PriorityClass"):                                     UnstructuredToTableFunc(SchedulingV1PriorityClassToTable),
	schedulingv1alpha1.SchemeGroupVersion.WithKind("PriorityClass"):                               UnstructuredToTableFunc(SchedulingV1alpha1PriorityClassToTable),
	schedulingv1beta1.SchemeGroupVersion.WithKind("PriorityClass"):                                UnstructuredToTableFunc(SchedulingV1beta1PriorityClassToTable),
	storagev1.SchemeGroupVersion.WithKind("CSIDriver"):                                            UnstructuredToTableFunc(StorageV1CSIDriverToTable),
	storagev1.SchemeGroupVersion.WithKind("CSINode"):                                              UnstructuredToTableFunc(StorageV1CSINodeToTable),
	storagev1.SchemeGroupVersion.WithKind("CSIStorageCapacity"):                                   UnstructuredToTableFunc(StorageV1CSIStorageCapacityToTable),
	storagev1.SchemeGroupVersion.WithKind("StorageClass"):                                         UnstructuredToTableFunc(StorageV1StorageClassToTable),
	storagev1.SchemeGroupVersion.WithKind("VolumeAttachment"):                                     UnstructuredToTableFunc(StorageV1VolumeAttachmentToTable),
	storagev1alpha1.SchemeGroupVersion.WithKind("CSIStorageCapacity"):                             UnstructuredToTableFunc(StorageV1alpha1CSIStorageCapacityToTable),
	storagev1alpha1.SchemeGroupVersion.WithKind("VolumeAttachment"):                               UnstructuredToTableFunc(StorageV1alpha1VolumeAttachmentToTable),
	storagev1alpha1.SchemeGroupVersion.WithKind("VolumeAttributesClass"):                          UnstructuredToTableFunc(StorageV1alpha1VolumeAttributesClassToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("CSIDriver"):                                       UnstructuredToTableFunc(StorageV1beta1CSIDriverToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("CSINode"):                                         UnstructuredToTableFunc(StorageV1beta1CSINodeToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("CSIStorageCapacity"):                              UnstructuredToTableFunc(StorageV1beta1CSIStorageCapacityToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("StorageClass"):                                    UnstructuredToTableFunc(StorageV1beta1StorageClassToTable),
	storagev1beta1.SchemeGroupVersion.WithKind("VolumeAttachment"):                                UnstructuredToTableFunc(StorageV1beta1VolumeAttachmentToTable),
	storagemigrationv1alpha1.SchemeGroupVersion.WithKind("StorageVersionMigration"):               UnstructuredToTableFunc(StoragemigrationV1alpha1StorageVersionMigrationToTable),
}
